import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const dom=new JSDOM('<div class="project-search"><input id="project-search"></div>',{url:'http://localhost/',runScripts:'outside-only'});
const w=dom.window;let mode='success',applied=null,fallbacks=0;
w.fetch=async()=>{if(mode==='fail')throw Error('offline');return {ok:true,json:async()=>({results:[{id:'kinondo'}]})};};
w.addEventListener('atlas-semantic-results',e=>{applied=e.detail;});
w.eval(fs.readFileSync('dist/semantic-search.js','utf8'));
const input=w.document.querySelector('input');const run=q=>{input.value=q;w.atlasPrimarySearch(q,()=>fallbacks++);};
run('Kenya');await new Promise(r=>setTimeout(r,350));assert.deepEqual(Array.from(applied.ids),['kinondo']);assert.equal(fallbacks,0);assert.ok(w.document.querySelector('.qmd-cloud').classList.contains('is-connected'));
mode='fail';run('screening');await new Promise(r=>setTimeout(r,350));assert.equal(fallbacks,1);assert.match(w.document.querySelector('[role=status]').getAttribute('aria-label'),/keyword search/);assert.equal(w.document.querySelector('.qmd-cloud').classList.contains('is-connected'),false);
run('other');assert.equal(fallbacks,2);run('');assert.equal(fallbacks,3);
dom.window.close();console.log('PASS primary results, failure fallback, cooldown, and empty search.');
