import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { pbkdf2Sync } from "node:crypto";
const dir = mkdtempSync(join(tmpdir(), "atlas-browser-"));
const password = process.env.ATLAS_TEST_PASSWORD;
if (!password)
  throw Error("Test password must be generated by Playwright config");
const salt = "isolated-browser-test";
const server = spawn(process.execPath, ["server/local.mjs"], {
  stdio: "inherit",
  env: {
    ...process.env,
    PORT: "8132",
    DATA_DIR: dir,
    PUBLIC_ORIGIN: "",
    ADMIN_PASSWORD_HASH:
      salt +
      ":" +
      pbkdf2Sync(password, salt, 100000, 32, "sha256").toString("hex"),
  },
});
for (const signal of ["SIGINT", "SIGTERM"])
  process.on(signal, () => server.kill(signal));
server.on("exit", (code) => {
  rmSync(dir, { recursive: true, force: true });
  process.exit(code || 0);
});
