import { build as bundle } from "esbuild";
import { renderSystemDiagrams } from "./render-system-diagrams.mjs";
import { generateSystemDiagrams } from "./system-diagrams.mjs";
import { createHash } from "node:crypto";
import fs from "node:fs";
// Readable source fragments compile to dependency-free browser assets.
const schema =
  "globalThis.AtlasSchema=" +
  fs.readFileSync("src/project-schema.json", "utf8") +
  ";\n";
fs.writeFileSync(
  "dist/search.js",
  schema + fs.readFileSync("src/search.js", "utf8"),
);
fs.writeFileSync(
  "dist/spreadsheet-format.js",
  schema + fs.readFileSync("src/spreadsheet-format.js", "utf8"),
);
fs.writeFileSync(
  "dist/admin.js",
  "// Generated by scripts/build.mjs; edit src/admin instead.\n(()=>{\n" +
    ["projects", "history", "settings", "navigation", "workspace"]
      .map((name) => fs.readFileSync("src/admin/" + name + ".js", "utf8"))
      .join("\n") +
    "\n})();\n" +
    fs.readFileSync("src/admin/transitions.js", "utf8"),
);
fs.writeFileSync(
  "dist/style.css",
  ["site", "admin"]
    .map((name) => fs.readFileSync("src/styles/" + name + ".css", "utf8"))
    .join("\n"),
);

// v3.0.0: derive secondary pages from the Atlas shell so headers/footers stay identical.
// Keep every page footer aligned with the package release version.
const { version } = JSON.parse(fs.readFileSync("package.json", "utf8"));
// Release builds share one version across the footer and Docker image tag.
if (fs.existsSync("compose.yaml"))
  fs.writeFileSync(
    "compose.yaml",
    fs
      .readFileSync("compose.yaml", "utf8")
      .replace(
        /hazlitt-creek-evidence-atlas:[\d.]+/,
        `hazlitt-creek-evidence-atlas:${version}`,
      ),
  );
const source = fs
  .readFileSync("dist/index.html", "utf8")
  .replace(
    /(<span class="site-version">)[^<]*(<\/span>)/,
    `$1Version ${version}$2`,
  );
fs.writeFileSync("dist/index.html", source);
const head = source
  .match(/<head>[\s\S]*?<\/head>/)[0]
  .replace(/<script[\s\S]*?<\/script>/g, "")
  .replace('href="style.css"', 'href="/style.css"');
const header = source
  .match(/<header>[\s\S]*?<\/header>/)[0]
  .replace('href="#"', 'href="/"');
const footer = source.match(/<footer>[\s\S]*?<\/footer>/)[0];
for (const [name, title] of [["admin", "Admin"]]) {
  const flipBootstrap = `<script>try{if(sessionStorage.getItem('atlas-editor-flip')&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('editor-flip-pending');setTimeout(()=>document.documentElement.classList.remove('editor-flip-pending'),3000);}}catch{}</script><style>.editor-flip-pending body{visibility:hidden}</style>`;
  const pageHead = head
    .replace("<head>", "<head>" + flipBootstrap)
    .replace(
      "<title>Hazlitt Creek Evidence Atlas</title>",
      `<title>${title} · Hazlitt Creek Evidence Atlas</title>`,
    )
    .replace(
      "</head>",
      `<script defer src="/config.js"></script><script defer src="/search.js"></script><script defer src="/theme.js"></script><script defer src="/external-links.js"></script><script defer src="/analytics-admin.js"></script><script defer src="/thesaurus-admin.js"></script><script defer src="/transfers.js"></script><script defer src="/${name}.js"></script></head>`,
    );
  fs.writeFileSync(
    `dist/${name}.html`,
    `<!doctype html><html lang="en">${pageHead}<body>${header}<main class="management-page"><nav class="page-navigation" aria-label="Management navigation"><a href="/">Back to Atlas</a><a href="/admin" ${name === "admin" ? 'aria-current="page"' : ""}>Admin</a></nav><h1>${title} ( ${version} )</h1><div id="${name}-page" class="${name === "log" ? "admin-section edit-log" : ""}"></div></main>${footer}</body></html>`,
  );
}
fs.copyFileSync(
  "node_modules/exceljs/dist/exceljs.min.js",
  "dist/exceljs.min.js",
);
fs.copyFileSync("node_modules/exceljs/LICENSE", "dist/exceljs-LICENSE.txt");
await bundle({
  entryPoints: ["src/system/admin-system.js"],
  bundle: true,
  minify: true,
  format: "iife",
  outfile: "dist/admin-system.js",
  logLevel: "warning",
});
const systemDiagrams = await renderSystemDiagrams(
  await generateSystemDiagrams(),
);
const assets = {};
for (const name of [
  "index.html",
  "admin.html",
  "app.js",
  "config.js",
  "semantic-search.js",
  "search.js",
  "external-links.js",
  "analytics-admin.js",
  "analytics-client.js",
  "analytics-interactions.js",
  "theme.js",
  "admin.js",
  "admin-system.js",
  "thesaurus-admin.js",
  "style.css",
  "map.svg",
  "transfers.js",
  "spreadsheet-worker.js",
  "spreadsheet-format.js",
  "exceljs.min.js",
  "exceljs-LICENSE.txt",
])
  assets["/" + name] = {
    body: fs.readFileSync("dist/" + name, "utf8"),
    type: {
      html: "text/html; charset=utf-8",
      js: "application/javascript; charset=utf-8",
      css: "text/css; charset=utf-8",
      svg: "image/svg+xml",
      txt: "text/plain; charset=utf-8",
    }[name.split(".").pop()],
  };
for (const asset of Object.values(assets).filter((a) =>
  a.type.startsWith("text/html"),
))
  asset.body = asset.body.replace(
    /(src|href)="(\/?[^"?]+\.(?:js|css))"/g,
    (all, attr, url) => {
      const target = assets[url.startsWith("/") ? url : "/" + url];
      return target
        ? `${attr}="${url}?v=${createHash("sha256").update(target.body).digest("hex").slice(0, 24)}"`
        : all;
    },
  );
for (const asset of Object.values(assets))
  asset.etag =
    '\"' +
    createHash("sha256").update(asset.body).digest("hex").slice(0, 24) +
    '\"';
fs.mkdirSync("dist/server", { recursive: true });
fs.mkdirSync("dist/.openai", { recursive: true });
fs.writeFileSync(
  "dist/server/index.js",
  "const SYSTEM_DIAGRAMS=" +
    JSON.stringify(systemDiagrams) +
    ";\n" +
    "const ASSETS=" +
    JSON.stringify(assets) +
    ";\nconst SEED=" +
    fs.readFileSync("data/seed.json") +
    ";\nconst COUNTRIES=" +
    fs.readFileSync("data/countries.json") +
    ";\n" +
    fs.readFileSync("dist/search.js", "utf8") +
    "\n" +
    fs.readFileSync("server/configuration.js", "utf8") +
    "\n" +
    fs.readFileSync("server/search-settings.js", "utf8") +
    "\n" +
    fs.readFileSync("server/transfers.js", "utf8") +
    "\n" +
    fs.readFileSync("server/analytics.js", "utf8") +
    "\nconst BACKUP_MIGRATIONS=" +
    JSON.stringify(
      fs
        .readdirSync("drizzle")
        .filter((n) => n.endsWith(".sql"))
        .sort(),
    ) +
    ";\n" +
    fs.readFileSync("server/backup.js", "utf8") +
    "\n" +
    fs.readFileSync("server/response-cache.js", "utf8") +
    "\n" +
    fs.readFileSync("server/search-sharing.js", "utf8") +
    "\n" +
    fs.readFileSync("server/worker.js", "utf8"),
);
fs.copyFileSync(".openai/hosting.json", "dist/.openai/hosting.json");
fs.cpSync("drizzle", "dist/.openai/drizzle", { recursive: true });
console.log("Worker built with embedded assets and migrations.");
